### PR TITLE
Added basic support to create journal entries.

### PR DESCRIPTION
**Pull request by dluxfordhpf**
1.  Added CreateGeneralLedgerTransaction operation.
2.  Added ledger transaction, entry, and custom field entities.
3.  Added serialization utilities.
4.  Added documentation on how to use all this.

### CODE REVIEW

**Comment by mteper** [comment]
David, thank you very much for the contribution!

## A few comments

### Style & Naming
 - please remove #regions (http://programmers.stackexchange.com/questions/53086/are-regions-an-antipattern-or-code-smell)
 - please use _underscoreCamelCase for class fields
 - please use PascalCase for class properties
 - please place entities in individual code files
 - please collapse whitespace before and after parentheses in method declarations, ex: `public void MyMethod(string a, string b)`
 - DRY, please use constructor fall-through, ex: `public Foo(string a, string b) : this(a) { B = b; }`
 - in a method like `AddEntryPair`, there is no reason to prefix every parameter with "new"

### Factoring
 - move JournalId_* fields into a dedicated static class named `JournalId`
 - use fast-bail-out for conditional logic -- it is far easier to reason about

Hard to read, especially with deep nesting:
```cs
string result = null;
if (condition)
{
  // lots of code
  result = "something real";
}
return result;
```

Easy to read, no nesting:
```cs
if (!condition) return null;

// lots of code
return "something real";
```
 - Let's not lose the benefit of strong typing that C# affords us. Instead of having a method that takes a bunch of strings, some of then that refer to one logical entity and some to another, let's instead formalize the logical entity into a class, and have the method accept two instances of that class as parameters.
 - Can we do better validating inputs? If Intacct API will balk at amounts that don't add up to zero, can we check that upfront?
 - Generally speaking, anything with `Utils` in the name is a code smell to me as it will invariably deteriorate into a general purpose, kitchen sink style, code dump. That aside, could you tell me what drove your design of serialization / deserialization vs. applying the model that is already there? I don't want to have two different approaches, but do want to make sure that if the existing approach is not good enough, that we extend it in a sensible way.

Git-wise, any future check-ins you push to your branch that originated this PR will automatically show up here, so there is nothing else you will need to do. Drop a note here when you've had a chance to make the changes and want me to review again (or, indeed any time, if you have questions / comments).

Thanks again!!

**Comment by dluxfordhpf** [comment]
OK, I can make those changes but it will take a little while.  There are some other perspectives on some of those ideas you might want to consider.  It’s funny how ideas become lost and rediscovered over time in the software industry, and in the meantime you have some bad ideas that are popular – the regions one in particular.  I’ve been doing this for 25 years on a lot of big and small products (e.g., half of everything AV with the name Symantec in front of it – SavCorp in particular) so I’ve learned a few things.  Here’s a few different ideas:

1.       Regions to group members are very helpful because they separate publics from privates in a very easy to read way.  They improve the signal to noise ratio, allow you to vary it, and maintain locality of code – all of which are important due to how our brains process information.  That makes handling code easier.  It’s rare that people misuse this.  That article highlights the only use of regions that I have seen to impede readability, use within a method, but the justification is incorrect – they were not built only for legacy code, plus he suggests a possible mistake people may take when seeing a region used with a problematic class and generalizes that to everyone/thing.  Reasons are important.

2.       Starting variable names with an _ roots from an old VB convention to workaround language limitations.  It’s both harder to type and distinguish the difference from the property it backs – a more verbose prefix or suffix is better, like property_.  The recommendation to prefix with _ is a bad idea.

3.       When a function has a single exit point, it is much easier to distinguish the flow of control.  This is an old and very good recommendation that originated with NetWare.

David L-

**Comment by dluxfordhpf** [comment]
It’s all done.  The reason for the Utils class is due to the serialization method used in this codebase, and for dealing with complex entities:

1.       Take a look at SerializeArrayOfChildIntacctObject.  This provides a generic way of serializing a list of Intacct child objects, instead of copying code.  The General Ledger Transaction object contains a list of GL entries and each entry contains a list of custom fields.  Duplicating the child object serialization would increase maintenance.  This also covers DeserializeArrayOfChildIntacctObject.

2.       The purpose of DeserializeXmlToString is to handle the fact that the host element for any particular item may not be present in the Intacct result set – you can ask it to return only a subset of fields.

3.       The purpose of SerializeStringToXml/SerializeChildIntacctObject is to minimize the size of the generated XML and permit field values to be optional as many are in the Intacct API.  The Intacct API calls out in many places a limit of 1,000 lines per request, so this permits us to reduce the size of a request so their XML gateway (apparently a PHP app) will have an easier time.

To your last point about client-side validation before posting to the server-side API, I did consider this and I think that’s reasonable, but a counter argument is that we don’t know all the validation that needs to be done, nor does Intacct document any of it.  Consequently you’re working against an unsure target.  I don’t think this is an entirely bad idea, but considered it unnecessary for the moment.

To expound a bit further on serialization, I think it would be a good idea to explore using XmlSerializer.  This would eliminate the hard-coded and importantly hand-synchronized strings, and permit attribute-based definition of much of the serialization process.  It would also, for example, eliminate all the Utils code I had to write to accommodate the more complexity entity relationships in serialization.  I’m planning on exploring this sometime in the next couple months when I have more time, but it will be a major change.

David L-

**Comment by mteper** [comment]
David,

These are all philosophical points, but for what it's worth, here's where I am coming from:

 1. To me, regions impede readability because they obscure that which I care about, which is code. If you have code that you would rather not see, it's hint for refactoring. I am not alone: http://anti-region-legion.org.
 1. Prefixing fields (*not* variables) with an underscore improves readability because at-a-glance you are able to tell a variable apart from a field.
 1. Single exit point is not an improvement in my eyes if it comes at a cost of forcing the reader of the code to maintain the active state/stack in their head.

The common thread here is readability and ease of maintenance. Since code is easily read 10x more often than it is written in general, and since as an open source project different people will come in over time to contribute, it is even more important to focus on readability and understandability.

Thanks for your understanding, or at least for agreeing to go along with it. :)

**Pull request merged**
